### ISSUE TITLE
Patch segmentation

### ISSUE THREAD

**Issue by dakomura** [AICAN-Research/breast-epithelium-segmentation#12]
Hello,

I have patch images extracted from breast cancer WSIs, but I don't have access to the full WSIs themselves. 
Is it possible to apply your model to these individual patches?
The microns per pixel (MPP) information is available for the patches.

Thank you for your assistance.

**Comment by mhoibo** [comment]
Hello, 
Thank you for your interest in our work. Yes, it should be possible to make it work. You could try two things: 
1. Might be a bit problematic depending on image level for extracted patches: 
```
image = '/path/to/image'
pipeline = fast.Pipeline.fromDataHub('breast-epithelium-segmentation', {'file': image})
pipeline.parse(visualization=False)
output = pipeline.getPipelineOutputData('segmentation')
# save segmentation as tiff:
fast.TIFFImagePyramidExporter.create('/path/to/save').connect(output).run()
```
2. or something like this (for expected x20 image): 
```
    path = '/path/to/image/'
    model = '/path/to/model/'  # can get model through FAST datahub
    importer_annotated = fast.ImageImporter.create(path)
    image = importer_annotated.runAndGetOutputData()
    
    generator = fast.PatchGenerator.create(2048, 2048, overlapPercent=0.3, maskThreshold=0.02).connect(0, image)
    #padder = PadderPO.create(width=2048, height=2048).connect(generator)
    patch_resizer = fast.ImageResizer.create(width=1024, height=1024, useInterpolation=False, preserveAspectRatio=True) \
        .connect(generator)
    network = fast.NeuralNetwork.create(modelFilename=model) \
        .connect(patch_resizer)
    converter = fast.TensorToSegmentation.create() \
        .connect(network)
   #fast.TensorToSegmentation.create(threshold=0.5).connect(0, network, 0)
    resizer = fast.ImageResizer.create(width=2048, height=2048, useInterpolation=False, preserveAspectRatio=True) \
        .connect(converter)

    stitcher = fast.PatchStitcher.create().connect(resizer)
    finished = fast.RunUntilFinished.create() \
        .connect(stitcher)
```
I hope you can make it work for your images!

**Comment by dakomura** [comment]
Thank you for your response!
I tried both approaches you suggested, but encountered some errors. I'd appreciate your guidance on resolving these issues.

For the first approach, I received the following error:
```
>>> output = pipeline.getPipelineOutputData('segmentation')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/komura/micromamba/envs/mmseg_py310/lib/python3.10/site-packages/fast/fast.py", line 19275, in getPipelineOutputData
    return *fast.Pipeline*getPipelineOutputData(self, name)
RuntimeError: OpenSlide was unable to open the file: ./left-31385_top-25657_bottom-27526_right-33254.png
```
It seems the pipeline is expecting a whole slide image format, but I'm working with PNG patches. Is there a way to adapt this method for png files?

For the second approach, I modified the code slightly to match my image dimensions and model path. 
```
path = './left-31385_top-25657_bottom-27526_right-33254.png'
model = './breast-tumour-segmentation-model/unet_tumour_refinement_model_fix-opset9.onnx'  

importer_annotated = fast.ImageImporter.create(path)
image = importer_annotated.runAndGetOutputData()

generator = fast.PatchGenerator.create(1024, 1024, overlapPercent=0.3, maskThreshold=0.02).connect(0, image)
#padder = PadderPO.create(width=2048, height=2048).connect(generator)
patch_resizer = fast.ImageResizer.create(width=512, height=512, useInterpolation=False, preserveAspectRatio=True) \
    .connect(generator)
network = fast.NeuralNetwork.create(modelFilename=model) \
    .connect(patch_resizer)
converter = fast.TensorToSegmentation.create() \
    .connect(network)
#fast.TensorToSegmentation.create(threshold=0.5).connect(0, network, 0)
resizer = fast.ImageResizer.create(width=1024, height=1024, useInterpolation=False, preserveAspectRatio=True) \
    .connect(converter)

stitcher = fast.PatchStitcher.create().connect(resizer)
finished = fast.RunUntilFinished.create() \
    .connect(stitcher)

finished.run()
```

However, I encountered this error:
```
RuntimeError: Input port 1 on process object NeuralNetwork is missing its required connection.
```
Could you please advise on this?

Thank you for your time and assistance.

**Comment by mhoibo** [comment]
Hi, 
I think you might be right, that when working with fast pipelines, the importer could be a WholeSlideImageImporter. I tried loading a .tiff and a .png like this:
```
   # works with .tiff and .png:
    importer = fast.ImageImporter.create(path)
    image = importer.runAndGetOutputData()
    
    # works only with .tiff, get the openslide error you got for .png
    importer = fast.WholeSlideImageImporter.create(path)
    image = importer.runAndGetOutputData()
```
The best way would possibly to open an issue in the FAST repository: https://github.com/smistad/FAST to see if smistad has a good solution to this.

For the second issue, I tested a bit today on a patch, and this seemed to work okay, though with overlap 0. I see however, that you are using the wrong model, which would probably lead to an error, the one you are using currently, belongs to this repository: https://github.com/AICAN-Research/H2G-Net 
If you want to use the epithelium segmentation, then you need to download and use the breast-epithelium-segmentation-model:  
```
path = '/path/to/image'
model = '.../FAST/datahub/breast-epithelium-segmentation-model/breast_epithelium_segmentation_single_output.onnx'
importer = fast.ImageImporter.create(path)
generator = fast.PatchGenerator.create(1024, 1024, maskThreshold=0.1, overlapPercent=0).connect(0, importer)
network = fast.SegmentationNetwork.create(modelFilename=model,  scaleFactor=1./255.).connect(generator)
stitcher = fast.PatchStitcher.create().connect(network)
finished = fast.RunUntilFinished.create().connect(stitcher)
finished = finished.runAndGetOutputData()
finished = finished.getAccess(fast.ACCESS_READ).getLevelAsImage(level=0)
plt.imshow(np.asarray(finished))
plt.show()
```
I hope this helps, let me know if it doesn't and i'll try to find the solution:)

**Comment by dakomura** [comment]
Thank you for your helpful response! 
I'm glad to report that the second approach using the breast-epithelium-segmentation-model worked successfully. Here's the specific code I used:
```
importer = fast.ImageImporter.create(path)
image = importer.runAndGetOutputData()
generator = fast.PatchGenerator.create(1024, 1024, overlapPercent=0.3, maskThreshold=0.1).connect(0, importer)
network = fast.SegmentationNetwork.create(modelFilename=model, scaleFactor=1./255.) \
    .connect(generator)
stitcher = fast.PatchStitcher.create().connect(network)
finished = fast.RunUntilFinished.create() \
    .connect(stitcher)
finished = finished.runAndGetOutputData()
```

I have a couple of questions regarding this implementation:

The images I want to process are at 40x magnification. Do I need to resize them before processing?
I noticed that when I set `overlapPercent=0`, the `finished = finished.runAndGetOutputData()` processing never completes. Is it okay to use `overlapPercent=0.3` instead?

Thank you again for your assistance.

**Comment by mhoibo** [comment]
Hi, I am sorry about the late reply. Yes, overlapPercent=0.3 should be good. If the images are not pyramidal then I would resize them, yes (to 1024 when through the network). If they are pyramidal, you should be able to put in magnification level 10 in the PatchGenerator. I hope this helps:)

**Comment by dakomura** [comment]
Thank you for your advice! 
I'll resize the original images to 1/4 of their size to process them as 10x images because they are not pyramidal.
